# Generated by Django 5.0.1 on 2024-01-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('R', 'Realizado')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
